server:
  port: 8082
  servlet:
    contextPath: /firstSpring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/azur_db
    username: root
    password: Password123
    driverClassName: com.mysql.cj.jdbc.Driver

paypal:
  client:
    id: ATgmIhDqdrWO8GxK9FkxMsrpt7l82U0SQX-0RAtQYbchkYrryCSQkiJsmYJYLdhmSAnPIWNnrmJyprog
    secret: EBJM-moOcgUIAfHytnNUY9Cs4YhgYOKYcUUtr8m_MV3Gfq44zjEbK4bs87byAjuufqeNVjbKXYxSNdG-
  mode: sandbox